services:
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/static/dist:/srv/static
      - $PWD/media:/srv/media
      - caddy_data:/data
      - caddy_config:/config
  django:
    build: $PWD/app
    volumes:
      - $PWD/app:/app
      - $PWD/data:/app/data
      - $PWD/import:/app/import
      - $PWD/media:/app/media
    environment:
      - DEBUG=1
      - SECRET_KEY=1234
      - RECONVERT_MEDIA=0
      - DATA_XLSX=/app/import/katalog_dla_kandydatów_na_kierowców_052026xlsx.xlsx
      - RESOURCES_ZIP=/app/import/multimedia_do_pytan.zip /app/import/Multimedia_do_pytań_-_cz_2_02042026.zip
volumes:
  caddy_data:
  caddy_config:
