# Generated by Django 6.0.5 on 2026-06-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('question_text', models.TextField(max_length=500, unique=True)),
                ('is_basic', models.BooleanField(default=True)),
                ('answer_A', models.TextField(blank=True, default='', max_length=500)),
                ('answer_B', models.TextField(blank=True, default='', max_length=500)),
                ('answer_C', models.TextField(blank=True, default='', max_length=500)),
                ('correct_answer', models.CharField(choices=[('A', 'a'), ('B', 'b'), ('C', 'c'), ('T', 'True'), ('F', 'False')], max_length=1)),
                ('media_url', models.URLField(blank=True, default='', max_length=500)),
                ('url_type', models.CharField(blank=True, choices=[('P', 'photo'), ('V', 'video')], default='', max_length=1)),
                ('number_of_points', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ManyToManyField(to='questions.categories')),
            ],
        ),
    ]
