FROM python:3.13

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN mkdir /app
WORKDIR /app

COPY requirements.txt /app
RUN pip install --upgrade pip && pip install -r requirements.txt

COPY . /app

RUN mkdir -p /app/data /app/media /app/import && \
    chmod +x /app/entrypoint.sh

VOLUME ["/app/data", "/app/import", "/app/media"]

ENTRYPOINT ["/app/entrypoint.sh"]

CMD ["gunicorn", "kierowcownik.wsgi:application", "--bind", "0.0.0.0:8000"]
